"""Initial migration.

Revision ID: 18068045f874
Revises: 
Create Date: 2022-04-08 23:10:32.227248

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '18068045f874'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('lists_groups',
    sa.Column('name', sa.String(length=20), nullable=False),
    sa.PrimaryKeyConstraint('name')
    )
    op.create_table('tasks_lists',
    sa.Column('name', sa.String(length=20), nullable=False),
    sa.Column('group_name', sa.String(length=20), nullable=True),
    sa.ForeignKeyConstraint(['group_name'], ['lists_groups.name'], ),
    sa.PrimaryKeyConstraint('name')
    )
    op.create_table('tasks',
    sa.Column('task_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('text', sa.String(length=200), nullable=True),
    sa.Column('completed', sa.Boolean(), nullable=True),
    sa.Column('list_name', sa.String(length=20), nullable=False),
    sa.ForeignKeyConstraint(['list_name'], ['tasks_lists.name'], ),
    sa.PrimaryKeyConstraint('task_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tasks')
    op.drop_table('tasks_lists')
    op.drop_table('lists_groups')
    # ### end Alembic commands ###
