version: "1"
services:
  webapp:
    build: .
    entrypoint: ["tail", "-f", "/dev/null"]
    volumes:
      - ..:/workspace
  postgres:
    image: "postgres:14.2"
    environment: 
      POSTGRES_HOST_AUTH_METHOD: trust
    
