"""initial migration

Revision ID: 68a0c99af01e
Revises: 
Create Date: 2022-04-23 22:42:16.106143

"""
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "68a0c99af01e"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "groups",
        sa.Column("group_id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("name", sa.String(length=20), nullable=True),
        sa.PrimaryKeyConstraint("group_id"),
        sa.UniqueConstraint("name"),
    )
    op.create_table(
        "collections",
        sa.Column("collection_id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("name", sa.String(length=20), nullable=True),
        sa.Column("group_name", sa.String(length=20), nullable=True),
        sa.ForeignKeyConstraint(
            ["group_name"],
            ["groups.name"],
        ),
        sa.PrimaryKeyConstraint("collection_id"),
        sa.UniqueConstraint("name"),
    )
    op.create_table(
        "tasks",
        sa.Column("task_id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("text", sa.String(length=200), nullable=True),
        sa.Column("completed", sa.Boolean(), nullable=True),
        sa.Column("collection_name", sa.String(length=20), nullable=False),
        sa.ForeignKeyConstraint(
            ["collection_name"],
            ["collections.name"],
        ),
        sa.PrimaryKeyConstraint("task_id"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("tasks")
    op.drop_table("collections")
    op.drop_table("groups")
    # ### end Alembic commands ###
