"""make some columns non-nullable

Revision ID: b67946c1de10
Revises: bcc40b349b1c
Create Date: 2022-05-22 17:55:51.030564

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b67946c1de10'
down_revision = 'bcc40b349b1c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('collections', 'name',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)
    op.alter_column('groups', 'name',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)
    op.alter_column('tasks', 'text',
               existing_type=sa.VARCHAR(length=200),
               nullable=False)
    op.alter_column('tasks', 'completed',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('tasks', 'completed',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('tasks', 'text',
               existing_type=sa.VARCHAR(length=200),
               nullable=True)
    op.alter_column('groups', 'name',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)
    op.alter_column('collections', 'name',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)
    # ### end Alembic commands ###
